@startuml

skinparam classAttributeIconSize 0

class Body {
- position : Vector
- velocity : Vector
- mass : double
+ move (f : Vector, dt : double)
+ forceFrom (b : Body) : Vector
+ toString()
}

class Universe {
- numBodies : int
- radius : double
+ Universe (fname : String)
+ update (dt : double)
}

class NBodySimulator {
- timeStep : double
- pauseTime : int
- trace : boolean

+ NBodySimulator (String fname : String, dt : double, pauseTime : int, do_trace : boolean)
+ drawUniverse()
+ simulate()
- createCanvas()
+ {static} main (args : String[])
}

class Vector {
- n : int
- data : double[n]
+ Vector (n : int)
+ Vector (data : double[])
+ lenght() : int
+ magnitude() : double
+ cartesian (i : int): double
+ direction() : Vector
+ plus (v : Vector) : Vector
+ minus (v : Vector) : Vector
+ scale (factor : double) : Vector
+ distanceTo (v : Vector) : double
+ dot (v : Vector) : double
+ toString() : String
}

Universe *-> "1..*" Body : bodies
NBodySimulator -> "1" Universe

note bottom of NBodySimulator
// in main() :
//...
// read bodies from file
nbody = new NBodySimulator(fname, dt, pauseTime, do_trace);
//...
nbody.simulate();
end note
@enduml